name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          known_hosts: unnecessary

      - name: Add Pantheon Remote and Push
        run: |
          git remote add pantheon ${{ secrets.PANTHEON_GIT_URL }}
          git push pantheon master --force